### ISSUE TITLE
Add Custom Starting Resolutions Setting

### ISSUE THREAD

**Issue by VGMRUS** [wyskoj/midis2jam2#129]
**Is your feature request related to a problem? Please describe.**

Adding this would make midis2jam2 WAY easier to record and add into any custom overlay for OBS since currently I have to use a third party program and press a weird keyboard combination just before midis2jam2 even opens to change it into the exact resolution I need, this would definitely would be useful for streamers that use overlays too

**Describe the solution you'd like**

In the graphic settings window on "Window Resolution" add inside a Custom resolution 1 and Custom resolution 2 (you can add more if you want but personally I only need 2)

And when the Custom resolution 1 or 2 is selected two boxes to input the exact resolution in pixels will appear, one for horizontal and another one for vertical, these numbers should be saved so you don't have to put them everytime you open midis2jam2

**Comment by wyskoj** [comment]
You can change the display resolution by editing the `graphics.properties` file located in the `.midis2jam2` folder, located in your user folder. If this file doesn't exist, open and close the enhanced graphics window—it should then appear. Enter the desired resolution after `resolution=` using an "x" as the separator. For example, you could have a custom resolution of 1234x5678:
```
#Tue Jul 26 17:44:05 EDT 2022
shadows=MEDIUM
resolution=1234x5678
antialiasing=LOW
```
Note, you cannot open the enhanced graphics window after setting a custom resolution because it doesn't recognize it as a valid resolution. However, you can edit this file manually to configure these settings.

**Comment by VGMRUS** [comment]
Nice, thanks for this information, it works perfectly
