### ISSUE TITLE
Absence of a tempo event at the beginning of MIDI file incurs a crash

### ISSUE THREAD

**Issue by Big-coconut** [wyskoj/midis2jam2#160]
**Describe the bug**
When I try to run the file, a popup says:
```
Error in Application

Uncaught exception thrown in Thread[jME3 Main,5,main]
NoSuchElementException: List contains no element matching the predicate.
```

**Offending MIDI file**
[Christmas_Medley.zip](https://github.com/wyskoj/midis2jam2/files/10328120/Christmas_Medley.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/85136770/210157732-73c8d7a1-3667-4006-a5c2-c77f48f9cfe9.png)

**System**
Windows 11

**Additional context**
It works on the original midijam.

**Comment by wyskoj** [comment]
This exception is thrown because midis2jam2 assumes there is a tempo event at the beginning of the file. I considered files that have zero tempo events, but not when the count is non-zero and the first event occurs after the beginning.

The fix is just to assume that the file starts at 120 BPM [per the SMF specification](http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html#:~:text=and%20the%20tempo%20120%20beats%20per%20minute).

**Comment by wyskoj** [comment]
A printout of the tempo events in the files reveals that the first tempo event occurs at 17760.

![image](https://github.com/wyskoj/midis2jam2/assets/31376393/45317409-7aac-4b49-84e8-9a3d43a61334)
